export const LOGIN_USER_SUCCESS= 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_START= 'LOGIN_USER_START';
export const LOGIN_USER_FAILURE= 'LOGIN_USER_FAILURE';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_START = 'GET_MESSAGES_START';
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';
